dsada

In [4]:
## 0) 행렬 정의
import numpy as np

# 두개의 2차원 정방행렬을 정의 N x N처럼 생긴 행렬
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [11]:
## 1) 행렬의 깁노 연산
# 행렬의 덧셈
C = A + B
print(C)

# 행렬의 곱셈(Hadamard Product, 원소곱)
D = A * B
print(D)

# 행렬의 곱셈(Matrix Product, 행렬곱)
E = A @ B
print(E)

# 원소 나눗셈(Element Division)
F = A / B
print(F)

# Matrix Square
G = A ** 2 # G = A @ A
print(G)

# 역행렬    
H = np.linalg.matrix_power(B, -1)
print(H)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]
[[-4.   3. ]
 [ 3.5 -2.5]]


In [ ]:
I = np.zeros((3, 3))
J = np.ones((3, 3))
K = np.empty((3, 3))
print(I)
print(J)
print(K)

# 단위행렬(정방행렬이 성립함) Identity Matrix
L = np.eye(3)

print(A @ H)

In [24]:
import numpy as np

np.random.seed(42)

# Uniform
random_integers = np.random.randint(low=0, high=10, size=5)
print("Integers:", random_integers)

random_floats = np.random.uniform(low=0.0, high=1.0, size=5)
print("Floats:", random_floats)

# Binomial
random_binomial = np.random.binomial(n=10, p=0.5, size=5)
print("Binomial:", random_binomial)

# Normal
random_normal = np.random.normal(loc=0, scale=1.0, size=5)
print("Normal:", random_normal)

# Exponential 지수 분포(Geometric)
random_exponential = np.random.exponential(scale=1.0, size=5)
print("Exponential:", random_exponential)

# Poisson
random_poisson = np.random.poisson(lam=1.0, size=5)
print("Poisson:", random_poisson)

Integers: [6 3 7 4 6]
Floats: [0.44583275 0.09997492 0.45924889 0.33370861 0.14286682]
Binomial: [6 3 6 7 0]
Normal: [ 0.02222183 -0.42779291 -0.53181741 -0.1174755   0.2220789 ]
Exponential: [0.48201466 4.08821653 0.6287891  1.96568728 1.1403958 ]
Poisson: [1 2 0 0 0]
